name: comeon
favicon: null
layout_spectrum: 0.89669
typography_spectrum: 0.8426518505439162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcd7d3'
    - '#644529'
    - '#a6886c'
    - '#6c9fa2'
    - '#060606'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
